name: Deploy Plugin to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código del repositorio
        uses: actions/checkout@v3

      - name: 🔧 Instalar lftp
        run: sudo apt-get install -y lftp

      - name: 🚀 Subir archivos del Plugin por SFTP
        run: |
          lftp -c "
            set sftp:auto-confirm yes;
            set net:max-retries 3;
            open sftp://${{ secrets.SFTP_USERNAME }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_SERVER }};
            mirror -R --delete \
              --exclude .git/ \
              --exclude .github/ \
              . /home/dh_4wwubs/toolkitmarcachile.laq.cl/wp-content/plugins/marcachile-toolkit-s3-plugin;
            bye
          "
